start-at-login = true
after-login-command = []
after-startup-command = [
  'exec-and-forget /opt/homebrew/opt/borders/bin/borders active_color=0xFFFFBE69 inactive_color=0xFF007692 width=8.0'
]
on-focused-monitor-changed = [
  'move-mouse monitor-lazy-center'
]
on-focus-changed = [
  'move-mouse window-lazy-center'
]
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'
key-mapping.preset = 'qwerty'

[gaps]
outer.bottom = 8
outer.top = 8
outer.left = 8
outer.right = 8
inner.horizontal = 8
inner.vertical   = 8

[exec]
inherit-env-vars = true

[exec.env-vars]
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[mode.main.binding]
cmd-shift-space = 'layout tiles'
cmd-shift-r = 'mode resize'
cmd-shift-keypadMinus = 'resize smart -50'
cmd-shift-keypadPlus = 'resize smart +50'
cmd-shift-w = 'close --quit-if-last-window'
cmd-shift-t = 'exec-and-forget open -n /Applications/kitty.app'
alt-f = 'fullscreen'
alt-shift-f  = 'macos-native-fullscreen'
cmd-left = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop left'
cmd-down = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop down'
cmd-up = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop up'
cmd-right = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop right'
cmd-shift-left = 'move left'
cmd-shift-down = 'move down'
cmd-shift-up = 'move up'
cmd-shift-right = 'move right'
alt-cmd = 'move-node-to-monitor --wrap-around next'
ctrl-cmd-b = 'balance-sizes'
cmd-1 = 'workspace --auto-back-and-forth 1'
cmd-2 = 'workspace --auto-back-and-forth 2'
cmd-3 = 'workspace --auto-back-and-forth 3'
cmd-4 = 'workspace --auto-back-and-forth 4'
cmd-5 = 'workspace --auto-back-and-forth 5'
cmd-6 = 'workspace --auto-back-and-forth 6'
cmd-7 = 'workspace --auto-back-and-forth 7'
cmd-8 = 'workspace --auto-back-and-forth 8'
cmd-9 = 'workspace --auto-back-and-forth 9'
cmd-0 = 'workspace --auto-back-and-forth 10'
cmd-minus = 'workspace --auto-back-and-forth 11'
cmd-equal = 'workspace --auto-back-and-forth 12'
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'
alt-shift-minus = 'move-node-to-workspace 11'
alt-shift-equal = 'move-node-to-workspace 12'
cmd-tab = 'workspace-back-and-forth'
cmd-shift-s = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

[mode.resize.binding]
keypadMinus = 'resize smart -50'
keypadPlus = 'resize smart +50'
left = 'resize width -64'
down = 'resize height -64'
up = 'resize height +64'
right = 'resize width +64'
esc = 'mode main'
enter = 'mode main'

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
run = ['layout tiling', 'move-node-to-workspace 1']
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout floating']