# basic colours
foreground #cecece
background #0e1415
selection_foreground #cecece
selection_background #293334
color0 #000000
color8 #777777
color1 #e25d56
color9 #f36868
color2 #73ca50
color10 #88db3f
color3 #e9bf57
color11 #f0bf7a
color4 #4a88e4
color12 #6f8fdb
color5 #915caf
color13 #e987e9
color6 #23acdd
color14 #4ac9e2
color7 #cecece
color15 #ffffff
cursor #cd974b
cursor_text_color #000000
url_color #cd974b

# window border colors and terminal bell colors
active_border_color #777777
inactive_border_color #323738
bell_border_color #e97e57

# tab bar colors
active_tab_foreground #cecece
active_tab_background #0e1415
inactive_tab_foreground #b8b8b8
inactive_tab_background #323738
