# shell
shell /bin/zsh

# theme
include current-theme.conf

# configs
allow_remote_control yes
map ctrl+shift+t new_tab   
map ctrl+shift+w close_tab
map ctrl+shift+left previous_tab
map ctrl+shift+right next_tab
show_tab_index yes 

# font
font_family JetBrainsMono Nerd Font
bold_font JetBrainsMono Nerd Font Bold
italic_font JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size 13

# terminal effects
background_opacity 0.85
macos_window_background_blur 20

# tab bar
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_min_tabs 1
